# -*- coding: utf-8 -*-
"""Acoustic Report Engine (ARE).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aOYYADX7AsCc-yTphj1gpMLVEk4qwJ8C
"""

pip install numpy scipy soundfile pyloudnorm

#!/usr/bin/env python3
import argparse
import numpy as np
import soundfile as sf
from scipy.signal import resample_poly, welch, convolve
import pyloudnorm as pyln
import os
import matplotlib.pyplot as plt
import google.colab.files

EPS = 1e-12

def dbfs_from_linear(x):
    return 20.0 * np.log10(np.maximum(x, EPS))

def linear_from_db(db):
    return 10.0 ** (db / 20.0)

def compute_metrics(sig, sr, ref_dbfs=-18.0):
    """
    Computes Peak, True Peak, and VU metrics based on standard ballistics.
    Standard Professional Calibration: 0 VU = -18 dBFS
    """
    # 1. Sample Peak
    peak_dbfs = dbfs_from_linear(np.max(np.abs(sig)))

    # 2. True Peak (ITU-R BS.1770-4 recommends 4x oversampling minimum)
    tp_oversample = 4
    tp_sig = resample_poly(sig, tp_oversample, 1)
    true_peak_dbfs = dbfs_from_linear(np.max(np.abs(tp_sig)))

    # 3. VU Meter Simulation (300ms integration window)
    vu_window_sec = 0.3
    win_len = max(1, int(vu_window_sec * sr))
    kernel = np.ones(win_len) / win_len
    # Mean Square energy moving average
    ms_env = convolve(sig**2, kernel, mode='same')
    rms_env = np.sqrt(np.maximum(ms_env, 0.0))

    # Map to VU: 0 VU = ref_dbfs (Standard: -18 dBFS)
    ref_lin = linear_from_db(ref_dbfs)
    vu_series = 20.0 * np.log10(np.maximum(rms_env / (ref_lin + EPS), EPS))

    return {
        'peak': peak_dbfs,
        'true_peak': true_peak_dbfs,
        'vu_avg': np.mean(vu_series),
        'vu_max': np.max(vu_series)
    }

def compute_loudness_standard(sig, sr):
    """
    Computes LUFS using ITU-R BS.1770-4 K-weighting.
    Manually implements sliding windows for ST and Momentary for maximum compatibility.
    """
    meter = pyln.Meter(sr)
    integrated = meter.integrated_loudness(sig)

    try:
        lra = pyln.features.loudness_range(sig, sr)
    except:
        lra = 0.0

    def get_sliding_lufs(window_sec):
        hop_sec = 0.1
        win_len = int(window_sec * sr)
        hop_len = int(hop_sec * sr)
        m = pyln.Meter(sr)
        louds = []
        for i in range(0, len(sig) - win_len, hop_len):
            segment = sig[i:i+win_len]
            louds.append(m.integrated_loudness(segment))
        return np.max(louds) if louds else integrated

    return {
        "integrated": float(integrated),
        "short_term_max": get_sliding_lufs(3.0),
        "momentary_max": get_sliding_lufs(0.4),
        "lra": lra
    }

def plot_pro_analysis(sig, sr):
    freqs, psd = welch(sig, sr, nperseg=4096)
    plt.figure(figsize=(16, 6))

    plt.subplot(1, 2, 1)
    plt.semilogx(freqs, 10 * np.log10(psd + EPS), color='#2ca02c')
    plt.title("Spectral Balance (Average EQ)", fontsize=12)
    plt.xlabel("Frequency (Hz)"); plt.ylabel("dB/Hz")
    plt.grid(True, which='both', alpha=0.3)
    plt.xlim(20, 20000)

    hop = int(0.05 * sr)
    num_blocks = len(sig) // hop
    truncated_sig = sig[:num_blocks * hop]
    rms_env = np.sqrt(np.mean(truncated_sig.reshape(-1, hop)**2, axis=1))
    rms_db = dbfs_from_linear(rms_env)
    times = np.linspace(0, len(sig)/sr, len(rms_db))

    plt.subplot(1, 2, 2)
    plt.fill_between(times, rms_db, -100, color='tab:blue', alpha=0.6)
    plt.title("Loudness Envelope (RMS over time)", fontsize=12)
    plt.xlabel("Time (s)"); plt.ylabel("dBFS")
    plt.ylim(-60, 0)
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.show()

def main():
    uploaded = google.colab.files.upload()
    if not uploaded: return

    fname = list(uploaded.keys())[0]
    data, sr = sf.read(fname, always_2d=True)
    sig = np.mean(data, axis=1).astype(np.float64)

    # Default VU ref adjusted to professional -18 dBFS
    metrics = compute_metrics(sig, sr, ref_dbfs=-18.0)
    loudness = compute_loudness_standard(sig, sr)

    print(f"\n{'='*50}\nTechnical Audio Report: {fname}\n{'-'*50}")
    print(f"Integrated Loudness:  {loudness['integrated']:.2f} LUFS")
    print(f"Short-term Max:       {loudness['short_term_max']:.2f} LUFS")
    print(f"Momentary Max:        {loudness['momentary_max']:.2f} LUFS")
    print(f"Loudness Range (LRA): {loudness['lra']:.2f} LU")
    print(f" ")
    print(f"True Peak:            {metrics['true_peak']:.2f} dBTP (ITU BS.1770)")
    print(f"Sample Peak:          {metrics['peak']:.2f} dBFS")
    print(f" ")
    print(f"VU Average:           {metrics['vu_avg']:.2f} VU (Ref: -18 dBFS)")
    print(f"VU Maximum:           {metrics['vu_max']:.2f} VU")
    print(f"{'='*50}")

    plot_pro_analysis(sig, sr)
    os.remove(fname)

if __name__ == '__main__':
    main()